package fr.edminecoreteam.api.management.list;

import java.util.HashMap;

public enum RankList {
//Non finalisé
    JOUEUR("§7Joueur", "§7Joueur", null),
    VIP("§F§lVIP", "§F§lVIP",null),
    SUPERVIP("§e§lSUPER-VIP", "§e§lSUPER-VIP", null),
    SUPREME("§a§lSUPREME", "§a§lSUPREME", null),
    ULTRA("§bULTRA","§bULTRA", null),
    ELITE("§3ELITE", "§3ELITE", null),
    FRIEND("&5FRIEND", "&5FRIEND", null),
    YTB("§cYOUTUBER", "§6INFLUENCE", null),
    STREAM("§5STREAMER", "§6INFLUENCE", null),
    FAMOUS("§6FAMOUS", "§6INFLUENCE", null),

    NGRAPH("§eSTAFF", "§2GRAPHISME", "NOVICE"),
    CGRAPHE("§eSTAFF", "§2GRAPHISME", "CONFIRMEE"),
    CGRAPH("§eSTAFF", "§2GRAPHISME", "CONFIRME"),
    EGRAPHE("§eSTAFF", "§2GRAPHISME", "EXPERTE"),
    EGRAPH("§eSTAFF", "§2GRAPHISME", "EXPERT"),

    NDESIGNW("§eSTAFF", "§1WEB DESIGN", "NOVICE"),
    CDESIGNWE("§eSTAFF", "§1WEB DESIGN", "CONFIRMEE"),
    CDESIGNW("§eSTAFF", "§1WEB DESIGN", "CONFIRME"),
    EDESIGNWE("§eSTAFF", "§1WEB DESIGN", "EXPERTE"),
    EDESIGNW("§eSTAFF", "§1WEB DESIGN", "EXPERT"),

    NDESIGNE("§eSTAFF", "§6ECO DESIGN", "NOVICE"),
    CDESIGNEE("§eSTAFF", "§6ECO DESIGN", "CONFIRMEE"),
    CDESIGNE("§eSTAFF", "§6ECO DESIGN", "CONFIRME"),
    EDESIGNEE("§eSTAFF", "§6ECO DESIGN", "EXPERTE"),
    EDESIGNE("§eSTAFF", "§6ECO DESIGN", "EXPERT"),

    NGDESIGN("§eSTAFF", "§3GAME DESIGN", "NOVICE"),
    CGDESIGNE("§eSTAFF", "§3GAME DESIGN", "CONFIRMEE"),
    CGDESIGN("§eSTAFF", "§3GAME DESIGN", "CONFIRME"),
    EGDESIGNE("§eSTAFF", "§3GAME DESIGN", "EXPERTE"),
    EGDESIGN("§eSTAFF", "§3GAME DESIGN", "EXPERT"),

    NTRADE("§eSTAFF", "§aTRADUCTRICE", "NOVICE"),
    NTRAD("§eSTAFF", "§aTRADUCTEUR", "NOVICE"),
    CTRADE("§eSTAFF", "§aTRADUCTRICE", "CONFIRMEE"),
    CTRAD("§eSTAFF", "§aTRADUCTEUR", "CONFIRME"),
    ETRADE("§eSTAFF", "§aTRADUCTICE", "EXPERTE"),
    ETRAD("§eSTAFF", "§aTRADUCTEUR", "EXPERT"),

    NREDACE("§eSTAFF", "§6REDACTRICE", "NOVICE"),
    NREDAC("§eSTAFF", "§6REDACTREUR", "NOVICE"),
    CREDACE("§eSTAFF", "§6REDACTRICE", "CONFIRMEE"),
    CREDAC("§eSTAFF", "§6REDACTEUR", "CONFIRME"),
    EREDACE("§eSTAFF", "§6REDACTRICE", "EXPERTE"),
    EREDAC("§eSTAFF", "§6REDACTEUR", "EXPERT"),

    NFEED("§eSTAFF", "§dFEEDBACK", "NOVICE"),
    CFEEDE("§eSTAFF", "§dFEEDBACK", "CONFIRMEE"),
    CFEED("§eSTAFF", "§dFEEDBACK", "CONFIRME"),
    EFEEDE("§eSTAFF", "§dFEEDBACK", "EXPERTE"),
    EFEED("§eSTAFF", "§dFEEDBACK", "EXPERT"),

    NCM("§eSTAFF", "§eCOMMUNITY MANAGER", "NOVICE"),
    CCME("§eSTAFF", "§eCOMMUNITY MANAGER", "CONFIRMEE"),
    CCM("§eSTAFF", "§eCOMMUNITY MANAGER", "CONFIRME"),
    ECME("§eSTAFF", "§eCOMMUNITY MANAGER", "EXPERTE"),
    ECM("§eSTAFF", "§eCOMMUNITY MANAGER", "EXPERT"),

    NANIME("§eSTAFF", "§2ANIMATRICE", "NOVICE"),
    NANIM("§eSTAFF", "§2ANIMATEUR", "NOVICE"),
    CANIME("§eSTAFF", "§2ANIMATRICE", "CONFIRMEE"),
    CANIM("§eSTAFF", "§2ANIMATEUR", "CONFIRME"),
    EANIME("§eSTAFF", "§2ANIMATRICE", "EXPERTE"),
    EANIM("§eSTAFF", "§2ANIMATEUR", "EXPERT"),

    NMODFE("§eSTAFF", "§9MODERATRICE FORUM", "NOVICE"),
    NMODF("§eSTAFF", "§9MODERATEUR FORUM", "NOVICE"),
    CMODFE("§eSTAFF", "§9MODERATRICE FORUM", "CONFIRMEE"),
    CMODF("§eSTAFF", "§9MODERATEUR FORUM", "CONFIRME"),
    EMODFE("§eSTAFF", "§9MODERATRICE FORUM", "EXPERTE"),
    EMODF("§eSTAFF", "§9MODERATEUR FORUM", "EXPERT"),

    NMODDE("§eSTAFF", "§9MODERATRICE DISCORD", "NOVICE"),
    NMODD("§eSTAFF", "§9MODERATEUR DISCORD", "NOVICE"),
    CMODDE("§eSTAFF", "§9MODERATRICE DISCORD", "CONFIRMEE"),
    CMODD("§eSTAFF", "§9MODERATEUR DISCORD", "CONFIRME"),
    EMODDE("§eSTAFF", "§9MODERATRICE DISCORD", "EXPERTE"),
    EMODD("§eSTAFF", "§9MODERATEUR DISCORD", "EXPERT"),

    NBUILDE("§aBUILDER", "§aBUILDEUSE", "NOVICE"),
    NBUILD("§aBUILDER", "§aBUILDEUR", "NOVICE"),
    CBUILDE("§aBUILDER", "§aBUILDEUSE", "CONFIRMEE"),
    CBUILD("§aBUILDER", "§aBUILDEUR", "CONFIRME"),
    EBUILDE("§aBUILDER", "§aBUILDEUSE", "EXPERTE"),
    EBUILD("§aBUILDER", "§aBUILDEUR", "EXPERT"),

    NHELPIG("§bHELPER", "§bHELPER", "NOVICE"),
    CHELPEIG("§bHELPER", "§bHELPER", "CONFIRMEE"),
    CHELPIG("§bHELPER", "§bHELPER", "CONFIRME"),
    EHELPEIG("§bHELPER", "§bHELPER", "EXPERTE"),
    EHELPIG("§bHELPER", "§bHELPER", "EXPERT"),

    NMODEIG("§9MOD", "§9MODERATRICE", "NOVICE"),
    NMODIG("§9MOD", "§9MODERATEUR", "NOVICE"),
    CMODEIG("§9MOD", "§9MODERATRICE", "CONFIRMEE"),
    CMODIG("§9MOD", "§9MODERATEUR", "CONFIRME"),
    EMODEIG("§9MOD", "§9MODERATRICE", "EXPERTE"),
    EMODIG("§9MOD", "§9MODERATEUR", "EXPERT"),

    SYSAD("§eSTAFF", "§5SYS.ADMIN", ""),

    NDEVE("§5DEV", "§5DEVELOPPEUSE AUTRE", "NOVICE"),
    NDEV("§5DEV", "§5DEVELOPPEUR AUTRE", "NOVICE"),
    CDEVE("§5DEV", "§5DEVELOPPEUSE AUTRE", "CONFIRMEE"),
    CDEV("§5DEV", "§5DEVELOPPEUR AUTRE", "CONFIRME"),
    EDEVE("§5DEV", "§5DEVELOPPEUSE AUTRE", "EXPERTE"),
    EDEV("§5DEV", "§5DEVELOPPEUR AUTRE", "EXPERT"),

    NDEVWE("§5DEV", "§5DEVELOPPEUSE WEB", "NOVICE"),
    NDEVW("§5DEV", "§5DEVELOPPEUR WEB", "NOVICE"),
    CDEVWE("§5DEV", "§5DEVELOPPEUSE WEB", "CONFIRMEE"),
    CDEVW("§5DEV", "§5DEVELOPPEUR WEB", "CONFIRME"),
    EDEVWE("§5DEV", "§5DEVELOPPEUSE WEB", "EXPERTE"),
    EDEVW("§5DEV", "§5DEVELOPPEUR WEB", "EXPERT"),

    NDEVDE("§5DEV", "§5DEVELOPPEUSE DISCORD", "NOVICE"),
    NDEVD("§5DEV", "§5DEVELOPPEUR DISCORD", "NOVICE"),
    CDEVDE("§5DEV", "§5DEVELOPPEUSE DISCORD", "CONFIRMEE"),
    CDEVD("§5DEV", "§5DEVELOPPEUR DISCORD", "CONFIRME"),
    EDEVDE("§5DEV", "§5DEVELOPPEUSE DISCORD", "EXPERTE"),
    EDEVD("§5DEV", "§5DEVELOPPEUR DISCORD", "EXPERT"),

    NDEVJE("§5DEV", "§5DEVELOPPEUSE JAVA", "NOVICE"),
    NDEVJ("§5DEV", "§5DEVELOPPEUR JAVA", "NOVICE"),
    CDEVJE("§5DEV", "§5DEVELOPPEUSE JAVA", "CONFIRMEE"),
    CDEVJ("§5DEV", "§5DEVELOPPEUR JAVA", "CONFIRME"),
    EDEVJE("§5DEV", "§5DEVELOPPEUSE JAVA", "EXPERTE"),
    EDEVJ("§5DEV", "§5DEVELOPPEUR JAVA", "EXPERT"),

    RESPBUILD("§4RESP", "§4RESPONSABLE", "BUILD"),
    RESPGAME("§4RESP", "§4RESPONSABLE", "GAME"),
    RESPCOM("§4RESP", "§4RESPONSABLE", "COM"),
    RESPDEV("§4RESP", "§4RESPONSABLE", "DEV"),
    RESPMOD("§4RESP", "§4RESPONSABLE", "MOD"),

    ADMINE("§cADMIN", "§cADMINISTRATRICE", ""),
    ADMIN("§cADMIN", "§cADMINISTRATEUR", "");


    private String display;
    private String rankTeam;
    private String rankLevel;

    public String getDisplay() {
        return display;
    }

    public String getRankTeam() {
        return rankTeam;
    }

    public String getRankLevel() {
        return rankLevel;
    }

    public String getRankName(){
        return rankTeam + " " + rankLevel;
    }



    RankList(String display, String rankTeam, String rankLevel) {
        this.display = display;
        this.rankTeam = rankTeam;
        this.rankLevel = rankLevel;
    }
}
